<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use MyPro\{Content,Database,Env};
$pdo=Database::connect(); $driver=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME); $auto=$driver==='mysql'?'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT';
$pdo->exec("CREATE TABLE IF NOT EXISTS users (id $auto, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'admin', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$pdo->exec("CREATE TABLE IF NOT EXISTS contents (id $auto, type VARCHAR(40) NOT NULL, title VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL, summary TEXT, body TEXT, image VARCHAR(255), status VARCHAR(20) NOT NULL DEFAULT 'draft', sort_order INTEGER NOT NULL DEFAULT 0, is_featured INTEGER NOT NULL DEFAULT 0, meta_title VARCHAR(190), meta_description VARCHAR(255), published_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(type,slug))");
try {$pdo->exec(($driver==='mysql'?'CREATE INDEX idx_contents_public':'CREATE INDEX IF NOT EXISTS idx_contents_public').' ON contents(type,status,sort_order)');} catch (Throwable) {}
$pdo->exec("CREATE TABLE IF NOT EXISTS inquiries (id $auto, full_name VARCHAR(150) NOT NULL, company VARCHAR(150), email VARCHAR(190) NOT NULL, phone VARCHAR(80), service VARCHAR(120), subject VARCHAR(190) NOT NULL, message TEXT NOT NULL, consent INTEGER NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'new', ip_hash VARCHAR(64), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
try {$pdo->exec(($driver==='mysql'?'CREATE INDEX idx_inquiries_status':'CREATE INDEX IF NOT EXISTS idx_inquiries_status').' ON inquiries(status,created_at)');} catch (Throwable) {}
$pdo->exec("CREATE TABLE IF NOT EXISTS settings (id $auto, name VARCHAR(120) NOT NULL UNIQUE, value TEXT, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$settings=['company_name'=>'Myprofessional Solutions, Inc.','tagline'=>'Making IT Simple','phone_primary'=>'+632 9177936188','phone_secondary'=>'+632 9992297632','email'=>'sales.myprosolinc@gmail.com','website'=>'www.myprosol.com'];
$exists=$pdo->prepare('SELECT COUNT(*) FROM settings WHERE name=?'); $insert=$pdo->prepare('INSERT INTO settings(name,value) VALUES(?,?)'); foreach($settings as $k=>$v){$exists->execute([$k]);if(!$exists->fetchColumn())$insert->execute([$k,$v]);}
$items=[
['service','IT Infrastructure','it-infrastructure','Resilient foundations for connected operations.','Structured cabling, network connectivity, data-center infrastructure, servers, storage, power protection, and physical security—planned and delivered around your operating requirements.'],
['service','Cybersecurity','cybersecurity','Practical protection across users, networks, and data.','Layered solutions spanning firewalls, antivirus, security appliances, intrusion prevention, web security, email security, and managed detection capabilities.'],
['service','Computing Devices','computing-devices','The right workplace technology, ready for business.','Business desktops, laptops, servers, storage, printers, CCTV, UPS systems, accessories, operating systems, productivity tools, and software licensing.'],
['service','Managed Services','managed-services','Specialist support that keeps your team moving.','Network administration, IT helpdesk, preventive maintenance, training, technical briefings, resource deployment, and Hybrid Security Operations Center services.'],
['service','Digital Transformation','digital-transformation','Technology aligned with how your organization works.','Consultancy, systems integration, application development, enterprise human capital management, and sustainable solar-energy solutions.'],
['solution','Hybrid Security Operations Center','hybrid-soc','Continuous security visibility with experienced support.','Managed security services delivered with portfolio-listed technology partners Sophos and Secureworks.'],
['solution','Data Center Design & Build','data-center-design-build','Infrastructure engineered as one dependable environment.','Servers, networking, storage, redundant power, environmental controls, fire suppression, telecom, workstations, and physical security.'],
['solution','Enterprise HCM','enterprise-hcm','Bring people operations into one connected platform.','Enterprise human capital management software from portfolio-listed product line ZingHR.'],
['industry','Large Enterprises','large-enterprises','Scalable solutions for complex environments.','Consultative planning, integration, managed support, security, and enterprise infrastructure.'],
['industry','Small & Medium Businesses','small-medium-businesses','Right-sized IT for growing organizations.','Secure, maintainable technology without unnecessary complexity.'],
['industry','SOHO & Retail','soho-retail','Dependable tools for daily operations.','Computing, connectivity, software, surveillance, printing, and power solutions.'],
['project','Sample: Multi-Site Network Modernization','sample-network-modernization','Demonstration case study — awaiting client verification.','A representative delivery approach covering discovery, structured connectivity, security controls, rollout planning, and support. This is sample content and does not represent a named MyPro client.'],
['testimonial','Sample Testimonial','sample-testimonial','Demonstration quote — not a verified customer endorsement.','“The team made a complex technology decision easier to understand.” Replace with a verified customer statement before publication.'],
['faq','What types of organizations does MyPro support?','organizations-supported','MyPro serves organizations across the Philippine market.','The portfolio identifies large enterprises, small and medium businesses, small offices/home offices, and the retail market.'],
['faq','Can MyPro combine products and services?','combined-solutions','Yes. Solutions are planned around the business need.','MyPro combines consultancy, systems integration, infrastructure, security, devices, software, and ongoing technical support as appropriate.'],
['faq','How do we start a consultation?','start-consultation','Tell us about your objectives and current environment.','Send an inquiry through the contact form. A MyPro representative can then clarify scope, priorities, and next steps.']];
$check=$pdo->prepare('SELECT COUNT(*) FROM contents WHERE type=? AND slug=?');$add=$pdo->prepare("INSERT INTO contents(type,title,slug,summary,body,status,sort_order,is_featured,published_at) VALUES(?,?,?,?,?,'published',?, ?, CURRENT_TIMESTAMP)"); foreach($items as $i=>$x){$check->execute([$x[0],$x[2]]);if(!$check->fetchColumn())$add->execute([$x[0],$x[1],$x[2],$x[3],$x[4],$i,($x[0]==='service'||$x[0]==='solution')?1:0]);}
$email=Env::get('ADMIN_EMAIL');$password=Env::get('ADMIN_PASSWORD');if($email&&$password){$q=$pdo->prepare('SELECT COUNT(*) FROM users WHERE email=?');$q->execute([strtolower($email)]);if(!$q->fetchColumn()){$pdo->prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)')->execute([Env::get('ADMIN_NAME','MyPro Administrator'),strtolower($email),password_hash($password,PASSWORD_DEFAULT),'admin']);echo "Administrator created.\n";}}
Content::clearCache();
echo "Database installed and portfolio content seeded.\n";
