<section class="hero"><div class="container hero-grid"><div><p class="eyebrow">Integrated IT solutions provider</p><h1>Technology that moves your business <em>forward.</em></h1><p class="lead">From secure infrastructure to managed support, MyPro simplifies technology decisions so your team can focus on what matters.</p><div class="actions"><a class="button" href="/contact">Request a Consultation →</a><a class="text-link" href="/services">Explore our services</a></div><div class="trust"><strong>Philippines-based expertise</strong><span>Infrastructure · Security · Transformation</span></div></div></div><p class="hero-tagline">Make IT simple</p></section>
<section class="logo-band"><div class="container"><p>Technology ecosystem represented in the MyPro portfolio</p><div class="logos"><b>Huawei</b><b>Sophos</b><b>PANDUIT</b><b>Cisco</b><b>Lenovo</b><b>Microsoft</b><b>HPE</b></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">What we do</p><h2>One partner for the technology behind your business.</h2></div><p>We bring strategy, products, implementation, and ongoing expertise together—without unnecessary complexity.</p></div><div class="cards numbered"><?php foreach($services as $i=>$service):?><a class="card" href="/services/<?=e($service['slug'])?>"><span class="number">0<?=$i+1?></span><h3><?=e($service['title'])?></h3><p><?=e($service['summary'])?></p><span class="arrow">Learn more →</span></a><?php endforeach;?></div></div></section>
<section class="section dark"><div class="container split"><div><p class="eyebrow cyan">Why MyPro</p><h2>Practical expertise.<br>End-to-end perspective.</h2><p>MyPro evolved from deep capability in networks, servers, applications, and technology supply into an integrated solutions provider.</p><a class="button light-button" href="/about">Discover our approach</a></div><div class="reasons"><article><span>01</span><div><h3>Consultative by design</h3><p>We align recommendations with real operational requirements.</p></div></article><article><span>02</span><div><h3>Broad solution capability</h3><p>Infrastructure, security, devices, software, and support work together.</p></div></article><article><span>03</span><div><h3>Built for continuity</h3><p>From deployment to preventive maintenance, we plan beyond go-live.</p></div></article></div></div></section>
<section class="section"><div class="container"><p class="eyebrow">Featured solutions</p><div class="section-head"><h2>Focused solutions for complex priorities.</h2><a class="text-link" href="/solutions">View all solutions</a></div><div class="feature-grid"><?php foreach($solutions as $s):?><a href="/solutions/<?=e($s['slug'])?>"><span>Solution</span><h3><?=e($s['title'])?></h3><p><?=e($s['summary'])?></p><b>Explore →</b></a><?php endforeach;?></div></div></section>
<section class="section pale"><div class="container split"><div><p class="eyebrow">How we work</p><h2>A clear path from challenge to outcome.</h2></div><ol class="process"><li><b>Discover</b><span>Understand priorities, risks, users, and environment.</span></li><li><b>Design</b><span>Shape a practical, scalable solution and delivery plan.</span></li><li><b>Deliver</b><span>Implement with disciplined coordination and validation.</span></li><li><b>Support</b><span>Maintain performance and help technology keep pace.</span></li></ol></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Who we serve</p><h2>Technology shaped around your organization.</h2></div><p>From enterprise environments to growing teams and daily retail operations, MyPro starts with the requirements that matter to you.</p></div><div class="industry-grid"><?php foreach($industries as $industry):?><a href="/industries/<?=e($industry['slug'])?>"><span aria-hidden="true">↗</span><h3><?=e($industry['title'])?></h3><p><?=e($industry['summary'])?></p></a><?php endforeach;?></div></div></section>
<?php if($projects):?><section class="section work"><div class="container"><div class="section-head"><div><p class="eyebrow cyan">Demonstration work</p><h2>A practical delivery approach, made visible.</h2></div><p>These sample scenarios illustrate how MyPro capabilities can come together. They are not claims about named customers.</p></div><div class="work-grid"><?php foreach($projects as $project):?><a href="/projects/<?=e($project['slug'])?>"><span class="sample-label">Sample · Awaiting verification</span><h3><?=e($project['title'])?></h3><p><?=e($project['summary'])?></p><b>View approach →</b></a><?php endforeach;?></div></div></section><?php endif;?>
<?php if($testimonials):?><section class="section testimonial"><div class="container"><p class="eyebrow">Sample testimonial</p><blockquote><?=e($testimonials[0]['body'])?></blockquote><p class="disclaimer">Demonstration content only — not a verified customer endorsement.</p></div></section><?php endif;?>
<section class="section"><div class="container faq-wrap"><div><p class="eyebrow">Questions, answered</p><h2>Frequently asked questions.</h2></div><div class="faqs"><?php foreach($faqs as $faq):?><details><summary><?=e($faq['title'])?></summary><p><?=e($faq['body'])?></p></details><?php endforeach;?></div></div></section>
<section class="cta"><div class="container"><div><p class="eyebrow cyan">Start a conversation</p><h2>Ready to make IT simpler?</h2></div><div><p>Tell us what your organization is working toward. We’ll help you identify the next practical step.</p><a class="button light-button" href="/contact">Talk to an IT Expert →</a></div></div></section>
